# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/cserv1_a/soc_ug/sc20j2t/Desktop/project/sc20j2t/CW2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/cserv1_a/soc_ug/sc20j2t/Desktop/project/sc20j2t/CW2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cserv1_a/soc_ug/sc20j2t/Desktop/project/sc20j2t/CW2/CMakeFiles /home/cserv1_a/soc_ug/sc20j2t/Desktop/project/sc20j2t/CW2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/cserv1_a/soc_ug/sc20j2t/Desktop/project/sc20j2t/CW2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named unit_tests

# Build rule for target.
unit_tests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 unit_tests
.PHONY : unit_tests

# fast build rule for target.
unit_tests/fast:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/build
.PHONY : unit_tests/fast

file_operations.o: file_operations.c.o
.PHONY : file_operations.o

# target to build an object file
file_operations.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_operations.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/file_operations.c.o
.PHONY : file_operations.c.o

file_operations.i: file_operations.c.i
.PHONY : file_operations.i

# target to preprocess a source file
file_operations.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_operations.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/file_operations.c.i
.PHONY : file_operations.c.i

file_operations.s: file_operations.c.s
.PHONY : file_operations.s

# target to generate assembly for a file
file_operations.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/file_operations.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/file_operations.c.s
.PHONY : file_operations.c.s

graphics.o: graphics.c.o
.PHONY : graphics.o

# target to build an object file
graphics.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/graphics.c.o
.PHONY : graphics.c.o

graphics.i: graphics.c.i
.PHONY : graphics.i

# target to preprocess a source file
graphics.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/graphics.c.i
.PHONY : graphics.c.i

graphics.s: graphics.c.s
.PHONY : graphics.s

# target to generate assembly for a file
graphics.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/graphics.c.s
.PHONY : graphics.c.s

logic.o: logic.c.o
.PHONY : logic.o

# target to build an object file
logic.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/logic.c.o
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/logic.c.o
.PHONY : logic.c.o

logic.i: logic.c.i
.PHONY : logic.i

# target to preprocess a source file
logic.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/logic.c.i
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/logic.c.i
.PHONY : logic.c.i

logic.s: logic.c.s
.PHONY : logic.s

# target to generate assembly for a file
logic.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/logic.c.s
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/logic.c.s
.PHONY : logic.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/main.c.s
.PHONY : main.c.s

tests.o: tests.c.o
.PHONY : tests.o

# target to build an object file
tests.c.o:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests.c.o
.PHONY : tests.c.o

tests.i: tests.c.i
.PHONY : tests.i

# target to preprocess a source file
tests.c.i:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests.c.i
.PHONY : tests.c.i

tests.s: tests.c.s
.PHONY : tests.s

# target to generate assembly for a file
tests.c.s:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/tests.c.s
.PHONY : tests.c.s

unity/src/unity.o: unity/src/unity.c.o
.PHONY : unity/src/unity.o

# target to build an object file
unity/src/unity.c.o:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.o
.PHONY : unity/src/unity.c.o

unity/src/unity.i: unity/src/unity.c.i
.PHONY : unity/src/unity.i

# target to preprocess a source file
unity/src/unity.c.i:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.i
.PHONY : unity/src/unity.c.i

unity/src/unity.s: unity/src/unity.c.s
.PHONY : unity/src/unity.s

# target to generate assembly for a file
unity/src/unity.c.s:
	$(MAKE) -f CMakeFiles/unit_tests.dir/build.make CMakeFiles/unit_tests.dir/unity/src/unity.c.s
.PHONY : unity/src/unity.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... rebuild_cache"
	@echo "... unit_tests"
	@echo "... file_operations.o"
	@echo "... file_operations.i"
	@echo "... file_operations.s"
	@echo "... graphics.o"
	@echo "... graphics.i"
	@echo "... graphics.s"
	@echo "... logic.o"
	@echo "... logic.i"
	@echo "... logic.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... tests.o"
	@echo "... tests.i"
	@echo "... tests.s"
	@echo "... unity/src/unity.o"
	@echo "... unity/src/unity.i"
	@echo "... unity/src/unity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

